# -*- coding: utf-8 -*-
"""TupleSetDictnory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eBUNhEl3jHM69TQBfl70CaWp0hydscEv
"""

n=int(input("enter the number of elemts\n"))
print("enter the elements\n")
t=()
l=[]
nt=()
for i in range(0,n):
  tu=input()
  l.append(tu)
t=tuple(l)
print("the old tuple is:\n")
print(t)

newt=list(set([i for i in l]))
print("the new tuple is\n")
nt=tuple(newt)
print(nt)

s1=set()
s2=set()
sn=set()
n = int(input('Enter no of elements in set 1: '))
m = int(input('Enter no of elements in set 2: '))
print("enter set1:\n")
for i in range(n):
  ch=input('enter value: ')
  s1.add(ch)
print('Enter set 2: ')
for i in range(m):
  ch = input('Enter value: ')
  s2.add(ch)   
print('Set 1: ',s1,'\nSet 2: ',s2)   

for x in s1:
  if x not in s2:
    sn.add(x)
for x in s2:
  if x not in s1:
    sn.add(x)
  
print('Result = ',sn)

#Python program to create a dictionary of phone numbers and names of five persons.
#Display the contents of the dictionary in alphabetical order of names.

dic={}
print("enter dictnory details")
for i in range(5):
  key=input("name: ")
  num=int(input("ph no: "))
  dic[key]=num

print("The dictnory before sorting is ",dic,"\nafter sofrting is:\n",sorted(dic.items()))

print("enter the book details")
bookshop={}
n=int(input("Enter the number of books: "))
for i in range(n):
  name=input("enter name: ")
  bookshop[name]=int(input("current number of copies: "))
ch=0
while(ch!=3):
        print('The current bookshop = \n',bookshop) 
        ch = int(input('1.Sell book\n2.Add book\n3.Stop\nEnter your choice: '))
        if(ch == 1):
            nam = input('Enter name of book: ')
            if nam not in bookshop:
                print('Wrong Input')
            else:
                cp = int(input('Enter the no of copies: '))
                bookshop[nam] -= cp
        elif ch == 2:
            nam = input('Enter name of book: ')
            if nam not in bookshop:
                print('Wrong Input')
            else:
                cp = int(input('Enter the no of copies: '))
                bookshop[nam] += cp

#Python program to create a dictionary with details(roll no, name, mark1, mark2, mark3) of 5 students. 
#Compute the total marks for each student and display the details.
#Also find the student with highest total.

dic={}
di={}
li=[]
for i in range(5):
  rn=int(input("roll no: "))
  name=input("name: ")
  m1=float(input("mark1: "))
  m2=float(input("mark2: "))
  m3=float(input("mark3: "))


  di["rollno"]=rn
  di["name"]=name
  di["mark1"]=m1
  di["mark2"]=m2
  di["mark3"]=m3

  dic=di.copy()
  li.append(dic)
print("the current list is:\n",l)

hm=0
id=0

for i in range(5):
  tm=li[i]['mark1']+li[i]['mark2']+li[i]['mark3']
  print("total marks of",li[i]['name'],"is",tm)
  if tm>hm:
    hm=tm
    id=i
print('student with highest total=',li[id]['name'])

